# Generated by Django 5.0.9 on 2025-10-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congratulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('poem_text', models.TextField(verbose_name='Текст стихотворения')),
                ('director_name', models.CharField(max_length=100, verbose_name='Имя директора')),
                ('director_position', models.CharField(max_length=100, verbose_name='Должность директора')),
                ('director_photo', models.ImageField(upload_to='congratulations/', verbose_name='Фото директора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Поздравление',
                'verbose_name_plural': 'Поздравления',
                'ordering': ['-created_at'],
            },
        ),
    ]
