# Generated by Django 5.0.9 on 2025-10-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congratulation',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='congratulation',
            name='director_photo',
        ),
        migrations.RemoveField(
            model_name='congratulation',
            name='director_position',
        ),
        migrations.AddField(
            model_name='congratulation',
            name='employee_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя сотрудника'),
        ),
        migrations.AddField(
            model_name='congratulation',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='congratulations/', verbose_name='Фото сотрудника'),
        ),
        migrations.AddField(
            model_name='congratulation',
            name='employee_position',
            field=models.CharField(default='', max_length=120, verbose_name='Должность сотрудника'),
        ),
    ]
