# Generated by Django 5.0.9 on 2025-10-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_congratulation_director_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('organization', models.CharField(max_length=200, verbose_name='Организация')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Логотип организации')),
                ('button_text', models.CharField(default='Подробнее', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
